### ISSUE TITLE
Example usage error

### ISSUE THREAD

**Issue by EthanHYX** [snkas/exputilpy#2]
while executing the following example usage code:
```
import exputil

local_shell = exputil.LocalShell()
print("There are %d screens active." % local_shell.count_screens())

remote_shell = exputil.RemoteShell("user", "example.com")
print("There are %d screens active on the remote." % remote_shell.count_screens())
```
Some thing is wrong:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print("There are %d screens active." % local_shell.count_screens())
  File "/home/ethan/anaconda3/envs/satnet/lib/python3.7/site-packages/exputil/shell.py", line 215, in count_screens
    res = self.valid_exec("screen -ls")
  File "/home/ethan/anaconda3/envs/satnet/lib/python3.7/site-packages/exputil/shell.py", line 211, in valid_exec
    self._raise_if_invalid(res)
  File "/home/ethan/anaconda3/envs/satnet/lib/python3.7/site-packages/exputil/shell.py", line 158, in _raise_if_invalid
    raise InvalidCommandError(res.output, res)
exputil.shell.InvalidCommandError: ('/bin/sh: 1: screen: not found\n', <exputil.shell.ShellExecResult object at 0x7f8fa081a450>)

**Comment by snkas** [comment]
Hi,

Not all Linux distributions have the screen command installed by default.
On Ubuntu: `sudo apt install screen`
